import Link from 'next/link';
import { APP_NAME, SITE_URL, EFFECTIVE_DATE, CONTACT_EMAIL } from '../../lib/legal';
import styles from '../legal.module.css';

export const metadata = {
  title: `Terms of Service · ${APP_NAME}`,
  description: `The rules for using ${APP_NAME}.`,
};

export default function TermsPage() {
  return (
    <main className={styles.page}>
      <h1 className={styles.title}>Terms of Service</h1>
      <p className={styles.meta}>Effective {EFFECTIVE_DATE} · {SITE_URL}</p>

      <div className={styles.summary}>
        <strong>The short version:</strong> you must be 18 or older. WiseGuy is AI entertainment:
        it swears, it can be wrong, and it is not a doctor, lawyer or therapist. Don&apos;t use it
        for anything illegal or to hurt anyone. It&apos;s free during the beta and comes with no
        guarantees.
      </div>

      <h2>1. Agreeing to these terms</h2>
      <p>
        By signing in to or using {APP_NAME} (&quot;the app&quot;), you agree to these terms and to
        our <Link href="/privacy">Privacy Policy</Link>. If you don&apos;t agree, don&apos;t use the app.
      </p>

      <h2>2. You must be 18 or older</h2>
      <p>
        The app contains explicit language and some personas include adult and romantic roleplay.
        You may only use it if you are at least 18 years old and allowed to use this kind of
        service where you live.
      </p>

      <h2>3. What the app is, and isn&apos;t</h2>
      <ul>
        <li>
          Replies are generated by AI models run by third parties. They can be inaccurate,
          offensive, made up or out of date. Check anything that matters before relying on it.
        </li>
        <li>
          Personas such as Therapist, Coach and Professional are characters.{' '}
          <strong>Nothing in the app is medical, mental-health, legal or financial advice.</strong>
        </li>
        <li>
          If you are in crisis or thinking about harming yourself or someone else, call or text
          <strong> 988</strong> (Suicide &amp; Crisis Lifeline, US) or call <strong>911</strong>.
          Don&apos;t rely on the app in an emergency.
        </li>
        <li>You are talking to an AI, not a person.</li>
      </ul>

      <h2>4. Your account</h2>
      <p>
        You sign in with your Google account. You are responsible for activity on your account and
        for keeping your Google account secure.
      </p>

      <h2>5. Acceptable use</h2>
      <p>You agree not to use the app to:</p>
      <ul>
        <li>create or request sexual content involving anyone under 18, or roleplay as or with a minor;</li>
        <li>break the law or help anyone else break it;</li>
        <li>harass, threaten, impersonate or share private information about real people;</li>
        <li>get real instructions for weapons, malware or other ways to cause serious harm;</li>
        <li>overload, attack, scrape or reverse-engineer the app, or get around its limits or locks;</li>
        <li>resell or redistribute access to the app.</li>
      </ul>
      <p>We may limit, suspend or remove access for anyone who breaks these rules.</p>

      <h2>6. Your content</h2>
      <p>
        What you type or say stays yours. You give us permission to send it to the AI services
        described in the Privacy Policy so the app can reply. You are responsible for what you do
        with the replies. They are generated by AI and may not be unique or accurate.
      </p>

      <h2>7. Plans, limits and changes</h2>
      <p>
        The app is free during the beta. We may add usage limits or paid plans later. Paid plans
        will come with their own terms, shown before you pay. We may change, pause or stop any part
        of the app at any time.
      </p>

      <h2>8. Third-party services</h2>
      <p>
        The app depends on services run by other companies (for example Google, Groq, Vercel and
        Neon). Their availability and their own terms are outside our control.
      </p>

      <h2>9. No warranty</h2>
      <p>
        The app is provided &quot;as is&quot; and &quot;as available&quot;, without warranties of
        any kind, to the fullest extent the law allows. We don&apos;t promise it will be
        uninterrupted, error-free or fit for any particular purpose.
      </p>

      <h2>10. Limitation of liability</h2>
      <p>
        To the fullest extent the law allows, we are not liable for any indirect, incidental or
        consequential damages, or for anything resulting from your use of AI-generated replies.
        Our total liability for any claim about the app is limited to the amount you paid us in
        the 12 months before the claim, which during the free beta is zero.
      </p>

      <h2>11. Ending your use</h2>
      <p>
        You can stop using the app at any time and ask us to delete your account (see the
        Privacy Policy). We may end or suspend access if these terms are broken or if we shut the
        app down.
      </p>

      <h2>12. Changes to these terms</h2>
      <p>
        We may update these terms. When we do, we will change the effective date at the top.
        Continuing to use the app after a change means you accept the new terms.
      </p>

      <h2>13. Contact</h2>
      <p>
        {CONTACT_EMAIL
          ? <>Questions about these terms: <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>.</>
          : <>A contact address for questions about these terms is coming soon.</>}
      </p>
    </main>
  );
}
